### ISSUE TITLE
Dashboard v3: Icons' feedback on :hover.

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#4413]
There are currently no visual feedback that we are hover an icon in the dashboard.

Something like the code below would be nice:

``` css
svg.icon:hover {
    fill: gray;
}
```
