### ISSUE TITLE
Add PHP nightly to the build

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#7636]
Adding early builds of new PHP versions will enable us to catch problems before they arise.

Here is an example I have from another repo.

```yml
php:
    - 7.1
    - 7.2
    - nightly

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true
```
