### ISSUE TITLE
Reference to vanillicon in dashboard/design/admin.css doesn't work for forums not at root

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/vanilla#8370]
Vanilla 2.8

In dashboard/design/admin.css, the URL for Vanillicon is not taking into account forums that are not at the root path. My forum is at https://greasyfork.org/forum/, and https://greasyfork.org/forum/applications/dashboard/design/admin.css?v=2.4.201 is referring to https://greasyfork.org/resources/fonts/vanillicon/vanillicon.eot and others, which is not correct. https://greasyfork.org/forum/resources/fonts/vanillicon/vanillicon.eot is correct.

**Comment by x00** [comment]
:+1:

**Comment by x00** [comment]
quick an dirty workaround place 

```css
@font-face {
  font-family: "vanillicon";
  src: url("../../../resources/fonts/vanillicon/vanillicon.eot");
  src: url("../../../resources/fonts/vanillicon/vanillicon.eot?#iefix") format("embedded-opentype"), url("../../../resources/fonts/vanillicon/vanillicon.woff") format("woff"), url("../../../resources/fonts/vanillicon/vanillicon.ttf") format("truetype"), url("../../../resources/fonts/vanillicon/vanillicon.svg?#vanillicon") format("svg");
  font-weight: normal;
  font-style: normal;
}
```

in your themes customadmin.css
