### ISSUE TITLE
Keystone: Mobile Mebox icons wrong alignment on Profile Page

### ISSUE THREAD

**Issue by igraziatto** [vanilla/vanilla#8483]
On Keystone/theme-boilerplate, icons on mobile Mebox navigation align to the left when user is on Profile Page:

  | Wrong: | Right: |
  | ------ | ------ |
  |    ![screen shot 2019-03-04 at 3 39 37 pm](https://user-images.githubusercontent.com/31521020/53761694-25b1c500-3e94-11e9-8034-ca7a4846e02e.png)    |    ![screen shot 2019-03-04 at 3 41 57 pm](https://user-images.githubusercontent.com/31521020/53761701-29dde280-3e94-11e9-81e1-5d7f1c8fa24a.png)    |

**Comment by charrondev** [comment]
I had this tiny fix for it in my recent community PR.

https://github.com/vanilla/community/pull/147/files#diff-bfec5d0d55fe8abe6f9871fc7e300e87R136

```css
// This should go back up to keystone.
.mobileMebox .WhoIs {
    width: 100%;
}
```
